obj-$(CONFIG_EXTERNAL_MISC_DRIVERS)	+= drivers/
obj-$(CONFIG_EXTERNAL_CAMERA)		+= camera/
#obj-$(CONFIG_EXTERNAL_BTNS_CAMERA)	+= camera_icgotm/
obj-$(CONFIG_EXTERNAL_CAMERA_IPU)	+= ipu/
obj-$(CONFIG_EXTERNAL_SILENT_LAKE)	+= silentlake/
